config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :castles do
    collection do
      get "search"
    end
  end
  # Nested routes for castles under users
  resources :users do
    resources :castles do
      resources :bookings do
        resources :reviews, only: [:new, :create]
      end
      resources :favourites, only: [:create, :destroy]
      post 'bookings/:id/approve', to: 'bookings#approve', as: 'approve_booking'
      post 'bookings/:id/deny', to: 'bookings#deny', as: 'deny_booking'
      delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
      get 'owner_bookings', to: 'bookings#owner', as: 'owner_bookings'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'

end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :castle
  belongs_to :user
  has_many :reviews
  validates :to, presence: true
  validates :from, presence: true
  validates :total_price, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings = current_user.bookings
  end

  def owner
    @owner_bookings = Booking.joins(:castle).where(castles: { user_id: current_user.id }).where.not(user_id: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
    @castle = Castle.find(params[:castle_id])
    @owner_bookings = Booking.joins(:castle).where(castles: { user_id: current_user.id }).where.not(user_id: current_user.id)
  end

  def new
    @castle = Castle.find(params[:castle_id])
    @booking = Booking.new
  end

  def create
    @castle = Castle.find(params[:castle_id])
    @booking = Booking.new(booking_params)
    @booking.castle = @castle
    @booking.user = current_user

    # Calculate duration
    duration = (@booking.to - @booking.from).to_i

    # Calculate total price (assuming price_per_day is a column in your Castle model)
    @booking.total_price = duration * @castle.price

    if @booking.save
      redirect_to user_castle_bookings_path(@castle), notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  def approve
    @booking = Booking.find(params[:id])

    if @booking.update(approved: true)
      redirect_to user_castle_booking_path(@booking), notice: 'Booking has been approved.'
    else
      redirect_to user_castle_booking_path(@booking), alert: 'Failed to approve booking.'
    end
  end

  def deny
    @booking = Booking.find(params[:id])

    if @booking.update(approved: false)
      redirect_to user_castle_booking_path(@booking), notice: 'Booking has been denied.'
    else
      redirect_to user_castle_booking_path(@booking), alert: 'Failed to deny booking.'
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_castle_bookings_path(current_user, @booking.castle), notice: 'Booking was successfully deleted.'
  end

  private

  def booking_params
    params.require(:booking).permit(:to, :from, :total_price, :castle_id)
  end
end

app/views/bookings/_index.html.erb
<div class="castle-header">
  <h2><%= current_user.first_name %>'s Bookings</h2>

  <%= link_to "Home", root_path, class: "btn btn-flat" %>
  <% if user_signed_in? %>
    <%= link_to "New Castle",  new_user_castle_path(current_user), class: "btn btn-flat" %>
  <% end %>
</div>


<div class="index-layout">
    <% @bookings.each do |booking| %>
      <%= link_to user_castle_booking_path(booking.user, booking.castle, booking) do %>
        <div class="castle-card-trip">
          <%= image_tag booking.castle.image, style: "width: 400px; height: 300px;", class: "castle-image" %>
          <i class="fa-regular fa-star toggle-star"></i>
          <div class="card-trip-infos">
            <div>
              <h3 class="castle-h3"><%= booking.castle.name %></h3>
            </div>
            <p class="castle-p"><%= booking.castle.location %></p>
            <p class="castle-p">To: <%= booking.to%>, From: <%= booking.from%></p>
            <h5 class="card-trip-pricing castle-h5">$<%= booking.total_price %></h5>
          </div>
        </div>
      <% end %>
      </a>
    <% end %>
</div>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['pk.eyJ1IjoiYW5kcmV3aHVsbWUiLCJhIjoiY2xzemNsMHdhMG15ZDJqcHEzaTl6bHoydCJ9.-c3JkqtXk5BETtCrUNP_hA'] %>">
</div>

<%= render "castles/footer" %>

app/views/bookings/index.html.erb
<div class="castle-header">
  <h2><%= current_user.first_name.capitalize %>'s Bookings</h2>

</div>
<!--
<div class="index-layout">
    <% @bookings.each do |booking| %>
      <%= link_to user_castle_booking_path(booking.user, booking.castle, booking) do %>
        <div class="castle-card-trip">
          <%= image_tag booking.castle.image, style: "width: 400px; height: 300px;", class: "castle-image" %>
          <i class="fa-regular fa-star toggle-star"></i>
          <div class="card-trip-infos">
            <div>
              <h3 class="castle-h3"></h3>
            </div>
            <p class="castle-p"><%= booking.castle.location %></p>
            <p class="castle-p">To: <%= booking.to%>, From: <%= booking.from%></p>
            <h5 class="card-trip-pricing castle-h5">$<%= booking.total_price %></h5>
          </div>
        </div>
      <% end %>
      </a>
    <% end %>
</div>
-->

<div class="bookings-container">
   <% @bookings.each do |booking| %>
    <%= link_to user_castle_booking_path(booking.user, booking.castle, booking) do %>
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <%= image_tag booking.castle.image, class: "img-fluid rounded-start"%>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><%= booking.castle.name %></h5>
            <p class="card-text overflow-ellipsis"><%= booking.castle.description %></p>
            <p class="card-text"><small class="text-muted"><%= (booking.to - booking.from).to_i.abs %> nights</small></p>
          </div>
        </div>
      </div>
      </div>
      <% end %>
   <% end %>
</div>

<%= render "castles/footer" %>

app/views/bookings/new.html.erb
<h1>Book a new castle</h1>

<%= link_to "View All Castles", castles_path(@castle), class: "btn btn-flat btn-new" %>

<div class="container py-5 form-center">
      <div class="bg-white rounded p-3 shadow form-style form-booking">
        <h3>Create a new castle listing</h3>
        <%= simple_form_for [current_user, @castle, @booking] do |f| %>
          <%= f.input :from, as: :date, input_html: { id: 'from-date' } %>
          <%= f.input :to, as: :date, input_html: { id: 'to-date' } %>
          <%# <%= f.input :total_price, input_html: { id: 'total-price', readonly: true } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
</div>
<%= render "castles/footer" %>

app/views/bookings/owner.html.erb
<div class="castle-header">
  <h2><%= current_user.first_name.capitalize %>'s Castles Bookings</h2>

  </div>
  <div class="bookings-container">
    <% @owner_bookings.each do |booking| %>
      <%= link_to user_castle_booking_path(booking.user, booking.castle, booking) do %>
      <div class="card mb-3">
        <div class="row g-0">
          <div class="col-md-4">
            <%= image_tag booking.castle.image, class: "img-fluid rounded-start"%>
          </div>
          <div class="col-md-8">
            <div class="card-body">
              <h5 class="card-title"><%= booking.castle.name %></h5>
              <p class="card-text overflow-ellipsis"><%= booking.castle.description %></p>
              <p class="card-text"><small class="text-muted"><%= (booking.to - booking.from).to_i.abs %> nights</small></p>
            </div>
          </div>
        </div>
        </div>
        <% end %>
    <% end %>
  </div>

</div>
<%= render "castles/footer" %>

app/views/bookings/show.html.erb
<div class="booking-center">
  <div class="castle-header">
    <h3><%= current_user.first_name.capitalize %>'s <%= @booking.castle.name %></h3>

    <% if current_user.id == @castle.user_id %>
      <%= link_to "View All Castles Bookings", user_castle_owner_bookings_path(current_user, current_user.castles), class: "btn btn-flat" %>
     <% else %>
      <%= link_to "View All Bookings", user_castle_bookings_path(current_user, @booking.castle.id), class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

<div class="booking-container">
    <%= image_tag @booking.castle.image, class: "card-img-top"%>
    <div class="card-body">
      <div class="card-title-head">
        <h5 class="card-title"><i class="fa-brands fa-fort-awesome"></i> <%=@booking.castle.name%></h5>
        <p class="card-text"><i class="fa-solid fa-location-dot"></i> <%=@booking.castle.location %></p>
      </div>
      <p class="card-text"><%=@booking.castle.description %></p>
      <div class="card-title-head border-bottom">
        <h3 class="card-text">Check In</h3>
        <h3 class="card-text">Check Out</h3>
      </div>
      <div class="card-text-date">
        <p class="card-text"><%= @booking.from.strftime('%d %B %Y') %></p>
        <p class="card-text"><%= @booking.to.strftime('%d %B %Y') %></p>
      </div>
      <div class="card-title-head border-bottom">
        <h3 class="card-text">Total Cost</h3>
      </div>
      <div class="card-title-cost">
        <p class="card-text">
        <%= (@booking.to - @booking.from).to_i.abs %> nights X   <i class="fa-solid fa-dollar-sign"></i><%= @castle.price %>  =
        <i class="fa-solid fa-dollar-sign"></i><%=@booking.total_price %></p>

      <div class="approval">
      <% if @booking.approved && @current_user.id == @castle.user_id %>
        <span class="card-text p-2 border text-success bg-dark">You have approved this booking</span>
      <% elsif @booking.approved  %>
        <span class="card-text p-2 border text-success bg-dark">Your bookings has been approved. Pack your bags</span>
       <% elsif @booking.approved == false && @current_user.id == @castle.user_id %>
        <span class="card-text border text-danger bg-dark p-2">You have denied this booking</span>
      <% elsif @booking.approved == false %>
         <span class="card-text border text-danger bg-dark p-2">Your bookings has been denied.</span>
      <% elsif @booking.approved == nil %>
        <% if current_user.id == @castle.user_id && @owner_bookings %>
       <!--   <%= link_to "Approve", "#", class: "btn btn-success approve-booking", data: { confirm: "Are you sure you want to approve this booking?", action: user_castle_approve_booking_path(@booking.user, @booking.castle, @booking) } %>
          <%= link_to "Deny", "#", class: "btn btn-danger deny-booking", data: { confirm: "Are you sure you want to deny this booking?", action: user_castle_deny_booking_path(@booking.user, @booking.castle, @booking) } %>-->

           <%= button_to "Approve",  user_castle_approve_booking_path(@booking.user, @booking.castle, @booking), class: "btn btn-success approve-booking", data: { method: :post, confirm: "Are you sure you want to approve this booking?"} %>
          <%= button_to "Deny", user_castle_deny_booking_path(@booking.user, @booking.castle, @booking), class: "btn btn-danger deny-booking", data: { method: :delete, confirm: "Are you sure you want to deny this booking?" } %>
        <% else %>
        <span class="card-text border border-secondary p-2 text-white-50 bg-dark"><strong>Pending approval ...</strong></span>
        <% end %>
      <% end %>
      </div>
      </div>

      <br>





  </div>
</div>

<%= render "castles/footer" %>

<!--
<script>
  function doSomething() {
    document.querySelectorAll('.approve-booking').forEach(function(link) {
    link.addEventListener('click', function(event) {
    event.preventDefault();
    var confirmMessage = this.getAttribute('data-confirm');
      if (confirm(confirmMessage)) {
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = this.getAttribute('data-action');
        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        var csrfParam = document.querySelector('meta[name="csrf-param"]').getAttribute('content');
        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = csrfParam;
        hiddenField.value = csrfToken;
        form.appendChild(hiddenField);
        document.body.appendChild(form);
        form.submit();
      }
    });
  });

  document.querySelectorAll('.deny-booking').forEach(function(link) {
    link.addEventListener('click', function(event) {
      event.preventDefault();
      var confirmMessage = this.getAttribute('data-confirm');
      if (confirm(confirmMessage)) {
        var form = document.createElement('form');
        form.method = 'POST';
        form.action = this.getAttribute('data-action');
        var csrfToken = document.querySelector('meta[name="csrf-token"]').getAttribute('content');
        var csrfParam = document.querySelector('meta[name="csrf-param"]').getAttribute('content');
        var hiddenField = document.createElement('input');
        hiddenField.type = 'hidden';
        hiddenField.name = csrfParam;
        hiddenField.value = csrfToken;
        form.appendChild(hiddenField);
        document.body.appendChild(form);
        form.submit();

      }
    });
  });
}

if (document.readyState === "loading") {
  // Loading hasn't finished yet
  document.addEventListener("DOMContentLoaded", doSomething);
} else {
  // `DOMContentLoaded` has already fired
  doSomething();
}
</script>
-->