config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :castles do
    collection do
      get "search"
    end
  end
  # Nested routes for castles under users
  resources :users do
    resources :castles do
      resources :bookings do
        resources :reviews, only: [:new, :create]
      end
      resources :favourites, only: [:create, :destroy]
      post 'bookings/:id/approve', to: 'bookings#approve', as: 'approve_booking'
      post 'bookings/:id/deny', to: 'bookings#deny', as: 'deny_booking'
      delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
      get 'owner_bookings', to: 'bookings#owner', as: 'owner_bookings'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'

end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">

    <%= link_to "#", class: "navbar-brand" do %>
      <span class="nav-btn-left" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="/home">Home</a>
        <a href="/about">About</a>
        <a href="/castles">Castles</a>
        <a href="/contact">Contact</a>
      </div>

        <script>
          function openNav() {
            document.getElementById("mySidenav").style.width = "100%";
          }

          function closeNav() {
            document.getElementById("mySidenav").style.width = "0";
          }
        </script>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-title">
      <h1><i class="fa-brands fa-fort-awesome-alt castle-icon"></i>CastlAway</h1>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.image.present? %>
              <%= image_tag current_user.image, class: "avatar"%>
              <% else %>
              <!-- Provide a default image if no image is attached to the user -->
              <%= image_tag "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBxa9qVd4KsVTu53JL_Prpx82NhTWV1m62cW6IrPBo3Q&s", class: "avatar" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My Bookings",  user_castle_bookings_path(current_user, current_user.castles), class: "dropdown-item" %>
              <%= link_to "My Castles Bookings",  user_castle_owner_bookings_path(current_user, current_user.castles), class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>