config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "pages#home"

  resources :castles do
    collection do
      get "search"
    end
  end
  # Nested routes for castles under users
  resources :users do
    resources :castles do
      resources :bookings do
        resources :reviews, only: [:new, :create]
      end
      resources :favourites, only: [:create, :destroy]
      post 'bookings/:id/approve', to: 'bookings#approve', as: 'approve_booking'
      post 'bookings/:id/deny', to: 'bookings#deny', as: 'deny_booking'
      delete 'bookings/:id', to: 'bookings#destroy', as: 'delete_booking'
      get 'owner_bookings', to: 'bookings#owner', as: 'owner_bookings'
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'
  get 'home', to: 'pages#home'

end

app/models/castle.rb
class Castle < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name_and_location,
    against: [:name, :location],
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews
  has_many :favourites
  has_many :fans, through: :favourites, source: :user
  validates :name, :location, :price, :description, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  def average_rating
    reviews.average(:rating).to_f || 0.0
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @castles = if params[:query].present?
      Castle.search_by_name_and_location(params[:query])
    else
      Castle.all
    end

    @markers = @castles.geocoded.map do |castle|
      {
        castle_id: castle.id, # Include castle_id attribute
        lat: castle.latitude,
        lng: castle.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {castle: castle}),
        marker_html: render_to_string(partial: "marker", locals: {castle: castle})
      }
    end
  end

  def show
    @castle = Castle.find(params[:id])
    @bookings = current_user.bookings if user_signed_in?
  end

  def new
    @user = User.find(params[:user_id])
    @castle = Castle.new
  end

  def create
    @user = User.find(params[:user_id])
    @castle = Castle.new(castle_params)
    @castle.user = @user

    if @castle.save
      redirect_to user_castles_path(@castle)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @castle = Castle.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @castle = Castle.find(params[:id])
    @castle.update(castle_params)
    redirect_to castle_path(@castle)
  end

  def destroy
    @user = User.find(params[:user_id])
    @castle = Castle.find(params[:id])
    @castle.destroy
    redirect_to root_path, notice: 'Castle listing was successfully deleted.'
  end

  def add_to_favorites
    session[:favourites] ||= []
    session[:favourites] << params[:id].to_i
    render json: { message: 'Castle has been favorited' }, status: :ok
  end

  def remove_from_favorites
    session[:favourites]&.delete(params[:id].to_i)
    render json: { message: 'Castle has been unfavorited' }, status: :ok
  end


  private

  def castle_params
    params.require(:castle).permit(:name, :location, :price, :description, :rating, :image, :user_id)
  end
end

app/views/castles/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by the boys!!
  </div>
</div>

app/views/castles/_info_window.html.erb
<h2><%= castle.name %></h2>
<p><%= castle.location %></p>

app/views/castles/_marker.html.erb
<%= image_tag "https://c0.klipartz.com/pngpicture/764/232/gratis-png-dormir-bella-castillo-castillo-disneyland-parque-disneyland-paris-centro-disneyland-hotel-hotel-thumbnail.png", height: 30, width: 30, alt: "Logo" %>

<div class="badge rounded-pill bg-primary fs-6">
  <%= castle.name %>
</div>

app/views/castles/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "MenuIcon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="nav-title">
      <h1>CastlAway</h1>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/castles/edit.html.erb
<h1>Edit castle</h1>

<%= link_to("Home", root_path, class: "btn btn-flat btn-new") %>

<div class="container py-5 form-center">
      <div class="bg-white rounded p-3 shadow form-style">
        <h3>Edit castle listing</h3>
        <%= simple_form_for [@user, @castle], url: user_castle_path(@castle), method: :patch do |f| %>
          <%= f.input :name, placeholder: 'Camelot' %>
          <%= f.input :location, placeholder: "55 Paris st France", input_html: {data:
              {address_autocomplete_target: "address"}},
              wrapper_html: {data: {controller: "address-autocomplete",
              address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
          <%= f.input :price, placeholder: '10000' %>
          <%= f.input :description, placeholder: 'An old fashioned, medievil style castle' %>
          <%= f.input :image, placeholder: 'image.jpg' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
</div>

<%= render "castles/footer" %>

app/views/castles/index.html.erb
<div class="index-top">
  <div class="castle-header">
    <h1>Castles</h1>

    <%= form_with(url: castles_path, method: "get", local: true) do |form| %>
    <%= form.text_field :query, placeholder: "Search by name or location" %>
    <%= form.submit "Search" %>
    <% end %>

    <%= link_to "Home", root_path, class: "btn btn-flat" %>
    <% if user_signed_in? %>
      <%= link_to "New Castle",  new_user_castle_path(current_user), class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

<div class="index-layout">
    <% @castles.each do |castle| %>
      <%= link_to castle_path(castle) do %>
        <div class="castle-card-trip">
          <%= image_tag castle.image, style: "width: 400px; height: 300px;", class: "castle-image" %>
          <% if user_signed_in?  && current_user.favourites.exists?(castle_id: castle.id) %>
          <!-- Show the filled star icon if the castle is favorited -->
            <i class="fas fa-star toggle-star" data-id="<%= castle.id %>"></i>
          <% else %>
          <!-- Show the empty star icon if the castle is not favorited -->
            <i class="far fa-star toggle-star" data-id="<%= castle.id %>"></i>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h3 class="castle-h3"><%= castle.name %></h3>
            </div>
            <p class="castle-p"><i class="fa-solid fa-location-dot logo-margin-right"></i><%= castle.location %></p>
            <h5 class="card-trip-pricing castle-h5">$<%= castle.price %></h5>
          </div>
        </div>
      <% end %>
      </a>
    <% end %>
</div>

<div class="map-container">
  <div class="map" style="width: 600px; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>



<%= render "castles/footer" %>

app/views/castles/new.html.erb
<h1>Add new castle</h1>

<%# <%= link_to("Home", root_path, class: "btn btn-flat") %>
<%= link_to "View All Castles", castles_path(@castle), class: "btn btn-flat btn-new" %>

<div class="container py-5 form-center">
      <div class="bg-white rounded p-3 shadow form-style form-new-castle">
        <h3>Create a new castle listing</h3>
        <%= simple_form_for [@user, @castle] do |f| %>
          <%= f.input :name, placeholder: 'Camelot' %>
          <%= f.input :location, placeholder: "55 Paris st France", input_html: {data:
              {address_autocomplete_target: "address"}},
              wrapper_html: {data: {controller: "address-autocomplete",
              address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
          <%= f.input :price, placeholder: '10000' %>
          <%= f.input :description, placeholder: 'An old fashioned, medievil style castle' %>
          <%= f.input :image, placeholder: 'image.jpg' %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    <div class="form-bottom"></div>
</div>

<%= render "castles/footer" %>

app/views/castles/show.html.erb
<div class="castle-center">
  <div class="castle-header show-header">
  <br class="show-br">
    <h1 class="show-h1"><%= @castle.name %></h1>

    <%= link_to "View All Castles", user_castles_path(@castle), class: "btn btn-flat btn-show-left-margin" %>
    <% if user_signed_in?  %>

      <% if current_user.id == @castle.user_id %>
        <%= link_to "Edit Castle",  edit_user_castle_path(@castle), class: "btn btn-flat" %>
        <%= link_to "Delete Castle", user_castle_path(current_user, @castle),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-flat" %>
      <% end %>
      <% if current_user.id != @castle.user_id %>
        <%= link_to "Book this Castle", new_user_castle_booking_path(current_user, @castle), class: 'btn btn-flat' %>
      <% end %>
    <% end %>
  </div>
  <br class="show-br">

  <div class="castle-show-body">
    <span><%= image_tag url_for(@castle.image), style: "width: 100%; height: auto;", class: "castle-image" %></span>

    <% if current_user.favourites.exists?(castle_id: @castle.id) %>
      <%= link_to "Unfavorite",  user_castle_favourite_path(current_user, @castle), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-danger btn-favourites btn-show-left-margin" %>
    <% else %>
      <%= link_to "Favorite", user_castle_favourites_path(current_user, @castle), data: {turbo_method: :post, turbo_confirm: "Are you sure?"}, class: "btn btn-flat btn-favourite btn-show-left-margin" %>
    <% end %>

    <div class="card-trip-infos">
      <div>
        <h2><%= @castle.name %></h2>

        <p class="castle-p"><%= @castle.description %></p>
        <p class="castle-p"><i class="fa-solid fa-location-dot logo-margin-right"></i><%= @castle.location %></p>
      </div>
    </div>
    <h5 class="card-trip-pricing castle-h5">$<%= @castle.price %></h5>
  </div>
</div>

<div class="reviews">
  <div class="reviews-header">
    <h2>Reviews</h2>
    <% capped_average_rating = [@castle.average_rating, 5].min %>
    <div class="star-rating" data-rating="<%= capped_average_rating %>">
      <h3>Average Rating: </h3>
      <% (1..5).each do |i| %>
        <% if i <= capped_average_rating %>
          <i class="fa-solid fa-star star active"></i>
        <% else %>
          <i class="fa-solid fa-star star"></i>
        <% end %>
      <% end %>
    </div>


<% if current_user.bookings.exists? %>
  <%= link_to "Leave a review", new_user_castle_booking_review_path(user_id: current_user.id, castle_id: @castle.id, booking_id: @bookings.first.id), class: 'btn btn-flat' %>
  <!-- Display other booking details as needed -->
<% end %>

  <div class="reviews-body">
    <% @castle.reviews.each do |review| %>
      <div class="review-card">
        <h6><%= review.user.first_name %></h6>
        <p><%= review.content %></p>
        <div class="card-rating">
        <div class="star-rating" data-rating="<%= review.rating %>">
          <% (1..5).each do |i| %>
            <% if i <= review.rating %>
              <i class="fa-solid fa-star star active"></i>
            <% else %>
              <i class="fa-solid fa-star star"></i>
            <% end %>
          <% end %>
        </div>
        <% capped_rating = [review.rating, 5].min %>
        <h6>Rating: <%= capped_rating %></h6>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render "castles/footer" %>


<script>
  $(document).on('click', '.star-rating .star', function() {
    var rating = $(this).data('value');
    $(this).closest('.star-rating').find('.star').removeClass('active');
    $(this).prevAll('.star').addBack().addClass('active');
  });
  $(document).ready(function() {
    $('.btn-favourite').on('click', function(e) {
      e.preventDefault();
      var id = $(this).data('id');
      var action = $(this).data('action');
      var button = $(this); // Store reference to the button

      console.log("Button clicked! Action:", action);

      var url = $(this).attr('href');

      $.ajax({
        type: 'POST',
        url: url,
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: { id: id },
        success: function(response) {
          // Your success handler code
         window.location.reload();
        },
        error: function(xhr, status, error) {
          // Your error handler code
        }
      });
    });
  });

  $(document).ready(function() {
    $('.btn-favourites').on('click', function(e) {
      e.preventDefault();
      var id = $(this).data('id');
      var action = $(this).data('action');
      var button = $(this); // Store reference to the button

      console.log("Button clicked! Action:", action);

      var url = $(this).attr('href');

      $.ajax({
        type: 'DELETE',
        url: url,
        headers: {
          'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: { id: id },
        success: function(response) {
          // Your success handler code
          window.location.reload();
        },
        error: function(xhr, status, error) {
          // Your error handler code
        }
      });
    });
  });
</script>



<!--
<script>
$(document).ready(function() {
  $('.btn-favourite').on('click', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var action = $(this).data('action');
    var button = $(this); // Store reference to the button

    var url = $(this).attr('href');

    $.ajax({
      type: 'POST',
      url: url,
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      },
      data: { id: id },
      success: function(response) {
        // Update button text and action
        button.text('Unfavorite');
        button.removeClass('btn-favourite').addClass('btn-favourites');
        button.data('action', 'unfavorite');

        // Update button click handler
        button.off('click');
        button.on('click', function(e) {
          unfavoriteCastle(e, id, url);
        });
      },
      error: function(xhr, status, error) {
        // Your error handler code
      }
    });
  });

  $('.btn-favourites').on('click', function(e) {
    e.preventDefault();
    var id = $(this).data('id');
    var action = $(this).data('action');
    var url = $(this).attr('href');

    unfavoriteCastle(e, id, url);
  });

  function unfavoriteCastle(e, id, url) {
    $.ajax({
      type: 'DELETE',
      url: url,
      headers: {
        'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
      },
      data: { id: id },
      success: function(response) {
        // Update button text and action
        $('.btn-favourites').text('Favorite');
        $('.btn-favourites').removeClass('btn-favourites').addClass('btn-favourite');
        $('.btn-favourite').data('action', 'favorite');

        // Update button click handler
        $('.btn-favourite').off('click');
        $('.btn-favourite').on('click', function(e) {
          favoriteCastle(e, id, url);
        });
      },
      error: function(xhr, status, error) {
        // Your error handler code
      }
    });
  }
});
</script>
-->